CREATE DATABASE DB_ESCOLA;
USE DB_ESCOLA;

CREATE TABLE TB_NOTAS(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR (2000),
SALA INT,
REGISTRO BIGINT,
NOTA FLOAT,
SITUACAO CHAR (255),
PRIMARY KEY (ID)
);

INSERT INTO TB_NOTAS(NOME, SALA, REGISTRO, NOTA, SITUACAO)
VALUES ("JOYCE SANTOS", 2, 455, 5.4,"REPROVADO");	

SELECT * FROM TB_NOTAS;

SELECT * FROM TB_NOTAS WHERE NOTA>7;
SELECT * FROM TB_NOTAS WHERE NOTA<7;

SET SQL_SAFE_UPDATES=0;
UPDATE TB_NOTAS SET NOTA=6 WHERE ID=8;
