CREATE DATABASE DB_HORTTIFRUTTI;
USE DB_HORTTIFRUTTI;

CREATE TABLE TB_CATEGORIAS(
ID BIGINT (5) AUTO_INCREMENT,
TIPO VARCHAR (255),
PROCESSO VARCHAR (255),
PRIMARY KEY (ID)
);

CREATE TABLE TB_PRODUTOS(
ID BIGINT (8) AUTO_INCREMENT,
VEGETAL VARCHAR (255),
MARCA VARCHAR (255),
VALOR DECIMAL (6,2),
QUANTIDADE BIGINT,
CATEGORIAS_ID BIGINT,
PRIMARY KEY (ID),
FOREIGN KEY (CATEGORIAS_ID) REFERENCES TB_CATEGORIAS(ID)
);


INSERT INTO TB_CATEGORIAS (TIPO, PROCESSO)
VALUES ("FRUTA","ORGÂNICO");
INSERT INTO TB_CATEGORIAS (TIPO, PROCESSO)
VALUES ("VERDURA","ORGÂNICO");
INSERT INTO TB_CATEGORIAS (TIPO, PROCESSO)
VALUES ("LEGUME","ORGÂNICO");
INSERT INTO TB_CATEGORIAS (TIPO, PROCESSO)
VALUES ("VERDURA"," NÃO ORGÂNICO");
INSERT INTO TB_CATEGORIAS (TIPO, PROCESSO)
VALUES ("LEGUME"," NÃO ORGÂNICO");

SELECT * FROM TB_CATEGORIAS;

INSERT INTO TB_PRODUTOS(VEGETAL,MARCA, VALOR, QUANTIDADE, CATEGORIAS_ID)
VALUES ("BANANA","CAMPO LIMPO", 13.45,6,1);
INSERT INTO TB_PRODUTOS(VEGETAL,MARCA, VALOR, QUANTIDADE, CATEGORIAS_ID)
VALUES ("CENOURA","CAMPO LIMPO", 6.5,3,3);
INSERT INTO TB_PRODUTOS(VEGETAL,MARCA, VALOR, QUANTIDADE, CATEGORIAS_ID)
VALUES ("ALFACE","HORTA JAO", 10.45,1,4);
INSERT INTO TB_PRODUTOS(VEGETAL,MARCA, VALOR, QUANTIDADE, CATEGORIAS_ID)
VALUES ("MAÇA","CAMPO LIMPO", 4.34,2,1);
INSERT INTO TB_PRODUTOS(VEGETAL,MARCA, VALOR, QUANTIDADE, CATEGORIAS_ID)
VALUES ("PERA","CAMPO LIMPO", 7.65,2,1);
INSERT INTO TB_PRODUTOS(VEGETAL,MARCA, VALOR, QUANTIDADE, CATEGORIAS_ID)
VALUES ("COUVE-FLOR","HORTA JOAO", 14.67,1,2);
INSERT INTO TB_PRODUTOS(VEGETAL,MARCA, VALOR, QUANTIDADE, CATEGORIAS_ID)
VALUES ("CEBOLA","MS", 13,3,5);
INSERT INTO TB_PRODUTOS(VEGETAL,MARCA, VALOR, QUANTIDADE, CATEGORIAS_ID)
VALUES ("MORANGO","CAMPO LIMPO", 20.45,2,1);

SELECT * FROM  TB_PRODUTOS;

SELECT * FROM TB_PRODUTOS WHERE 5<VALOR AND VALOR<15;

SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS
ON TB_PRODUTOS.CATEGORIAS_ID=TB_CATEGORIAS.ID;

-- SELECT * FROM TB_PRODUTOS FULL  JOIN TB_CATEGORIAS ON 
-- TB_PRODUTOS.CATEGORIAS_ID = TB_CATEGORIAS.ID;