CREATE DATABASE DB_PIZZARIALEGAL;
USE DB_PIZZARIALEGAL;

CREATE TABLE TB_CATEGORIAS(
ID BIGINT (5) AUTO_INCREMENT,
TIPO VARCHAR (255),
TAMANHO VARCHAR (255),
PRIMARY KEY (ID)
);

CREATE TABLE TB_PIZZAS(
ID BIGINT (8) AUTO_INCREMENT,
SABOR VARCHAR (255),
PRECO DECIMAL (6),
BORDA VARCHAR (255),
MOLHO VARCHAR (255),
CATEGORIA_ID BIGINT,
PRIMARY KEY (ID),
FOREIGN KEY (CATEGORIA_ID) REFERENCES TB_CATEGORIAS (ID)
);

-- TABELA CATEGORIAS
INSERT INTO TB_CATEGORIAS(TIPO, TAMANHO)
VALUES ("DOCE","PEQUENA");
INSERT INTO TB_CATEGORIAS(TIPO, TAMANHO)
VALUES ("DOCE","GRANDE");
INSERT INTO TB_CATEGORIAS(TIPO, TAMANHO)
VALUES ("SALGADA","PEQUENA");
INSERT INTO TB_CATEGORIAS(TIPO, TAMANHO)
VALUES ("SALGADA","MÉDIA");
INSERT INTO TB_CATEGORIAS(TIPO, TAMANHO)
VALUES ("SALGADA","GRANDE");

SELECT * FROM TB_CATEGORIAS;

-- Tabela Pizzas
INSERT INTO TB_PIZZAS(SABOR, PRECO, BORDA, MOLHO, CATEGORIA_ID)
VALUES("MARGUERITA",45.98," CATUPIRY", "TRADICIONAL", 5); -- PREÇO ARREDONDOU PARA FAZER CORREÇÃO ARRUMAR DECIMAL
INSERT INTO TB_PIZZAS(SABOR, PRECO, BORDA, MOLHO, CATEGORIA_ID)
VALUES("MUSSARELA",67.45,"-", "DU CHEF", 4);
INSERT INTO TB_PIZZAS(SABOR, PRECO, BORDA, MOLHO, CATEGORIA_ID)
VALUES("ROMEU E JULIETA",42.56,"NUTELLA", "-", 1);
INSERT INTO TB_PIZZAS(SABOR, PRECO, BORDA, MOLHO, CATEGORIA_ID)
VALUES("CALABRESA",42.79," CATUPIRY", "TRADICIONAL", 3);
INSERT INTO TB_PIZZAS(SABOR, PRECO, BORDA, MOLHO, CATEGORIA_ID)
VALUES("NUTELLA",56.78," NUTELLA", "-", 2);
INSERT INTO TB_PIZZAS(SABOR, PRECO, BORDA, MOLHO, CATEGORIA_ID)
VALUES("PORTUGUESA",87.9," CATUPIRY", "ESPECIAL", 4);
INSERT INTO TB_PIZZAS(SABOR, PRECO, BORDA, MOLHO, CATEGORIA_ID)
VALUES("BRIGADEIRO",42.98,"-", "-", 1);
INSERT INTO TB_PIZZAS(SABOR, PRECO, BORDA, MOLHO, CATEGORIA_ID)
VALUES("QUATRO QUEIJOS",67.89," CHEDDAR", "TRADICIONAL", 5);


SELECT * FROM TB_PIZZAS;

SELECT * FROM TB_PIZZAS WHERE PRECO<45;
SELECT * FROM TB_PIZZAS WHERE 50<PRECO AND PRECO<100;

SELECT * FROM TB_PIZZAS 
INNER JOIN TB_CATEGORIAS ON TB_PIZZAS.CATEGORIA_ID = TB_CATEGORIAS.ID;

SELECT * FROM TB_PIZZAS 
INNER JOIN TB_CATEGORIAS ON TB_PIZZAS.CATEGORIA_ID = TB_CATEGORIAS.ID;

SELECT * FROM TB_PIZZAS 
INNER JOIN TB_CATEGORIAS ON TB_PIZZAS.CATEGORIA_ID = TB_CATEGORIAS.ID 
WHERE CATEGORIA_ID=1 OR CATEGORIA_ID=2;