CREATE DATABASE DB_SERVICO_RH;
USE DB_SERVICO_RH;

CREATE TABLE TB_COLABORADORES (
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR (1000),
IDADE INT,
SETOR CHAR (200),
TURNO CHAR (3),
SALARIO INT,
PRIMARY KEY (ID)
);

INSERT INTO TB_COLABORADORES (NOME, IDADE, SETOR, TURNO, SALARIO)
VALUES ("NATHALIA G. OLIVEIRA", 21, "ADM", "A", 3456);
INSERT INTO TB_COLABORADORES (NOME, IDADE, SETOR, TURNO, SALARIO)
VALUES ("CAROLYNE M. NASCIMENTO", 32, "QUALIDADE", "B", 2345);
INSERT INTO TB_COLABORADORES (NOME, IDADE, SETOR, TURNO, SALARIO)
VALUES ("MARCOS BARBOZA", 32, "CONTABILIDADE", "C", 1987);
INSERT INTO TB_COLABORADORES (NOME, IDADE, SETOR, TURNO, SALARIO)
VALUES ("HELENA SILVA", 43, "GERENCIA", "B", 7890);
INSERT INTO TB_COLABORADORES (NOME, IDADE, SETOR, TURNO, SALARIO)
VALUES ("SANDRO GOMES", 45, "LIMPEZA", "C", 1976);

SELECT * FROM TB_COLABORADORES WHERE SALARIO>2000;

SELECT * FROM TB_COLABORADORES WHERE SALARIO<2000;

UPDATE TB_COLABORADORES SET SALARIO=2345 WHERE ID=2;

SELECT * FROM TB_COLABORADORES;

