CREATE DATABASE DB_GALERIA_ART;
USE DB_GALERIA_ART;

CREATE TABLE TB_ARTES(
ID BIGINT AUTO_INCREMENT,
TIPO CHAR (255),
TITULO VARCHAR (2500),
AUTOR VARCHAR (2500),
ANO INT,
VALOR FLOAT,
PRIMARY KEY (ID)
);

INSERT INTO TB_ARTES(TIPO, TITULO, AUTOR, ANO, VALOR)
VALUES ("VASO CERÂMICO", "HISTÓRIA DE GAIA", "JIN HAYA", 1876, 1234);
INSERT INTO TB_ARTES(TIPO, TITULO, AUTOR, ANO, VALOR)
VALUES ("QUADRO", "DIA ENSOLARADO", "VINI DERT", 2009, 345.78);
INSERT INTO TB_ARTES(TIPO, TITULO, AUTOR, ANO, VALOR)
VALUES ("QUADRO", "RETRATO DE UM VAMPIRO", "JOHN SANDERZ", 1767, 2134.67);
INSERT INTO TB_ARTES(TIPO, TITULO, AUTOR, ANO, VALOR)
VALUES ("ESCULTURA", "BUSTO D'ALMA", "SANDRA NUNES", 1987, 487.90);
INSERT INTO TB_ARTES(TIPO, TITULO, AUTOR, ANO, VALOR)
VALUES ("ESCULTURA", "BUSTO D'ALMA", "SANDRA NUNES", 1987, 487.90);
INSERT INTO TB_ARTES(TIPO, TITULO, AUTOR, ANO, VALOR)
VALUES ("QUADRO", "PARAISO", "JESSICA CHAINSTAIN", 2009, 4956.30);
INSERT INTO TB_ARTES(TIPO, TITULO, AUTOR, ANO, VALOR)
VALUES ("ESCULTURA", "LIBERDADE", "ROBERTO ALVES", 1876, 1234.89);

SELECT * FROM TB_ARTES;

DELETE FROM TB_ARTES WHERE ID= 5; 
DELETE FROM TB_ARTES WHERE ID= 6;
DELETE FROM TB_ARTES WHERE ID= 7;   

SELECT * FROM TB_ARTES WHERE VALOR>500;
SELECT * FROM TB_ARTES WHERE VALOR<500;

SET SQL_SAFE_UPDATES=0;

UPDATE TB_ARTES SET TIPO="CERÂMICA" WHERE ID=1;